version: "3.8"

x-logging:
  &default-logging
  options:
    max-size: "200k"
    max-file: "10"


services:

  nginx:
    image: nginx:1.23.3-alpine
    logging: *default-logging
    container_name: nginx
    restart: always
    ports:
      - "80:80"        # MQTT over unencrypted WebSockets
      - "8888:8888"    # MQTT over unencrypted TCP
      - "443:443"      # MQTT over encrypted TCP/WebSockets ??
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/openssl:/etc/ssl
      - ./public:/public
    depends_on:
      rabbit:
        condition: service_healthy

  rabbit:
    image: mqtt_rabbit:latest
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
      - 15675:15675   # web-mqtt (ws)
      - 1883:1883     # mqtt
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s  # The interval between health checks
      timeout: 10s  # Timeout for each health check
      retries: 5  # Number of retries before considering the container unhealthy
